# docker-compose.yml

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  ms-catalogo:
    build: ./ms-catalogo
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  ms-compras:
    build: ./ms-compras
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  ms-inventario:
    build: ./ms-inventario
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  ms-pagos:
    build: ./ms-pagos
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  orquestador:
    build: ./orquestador
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
