
services:
  ms-catalogo:
    build: ./ms-catalogo
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  ms-compras:
    build: ./ms-compras
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

  ms-inventario:
    build: ./ms-inventario
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork


  ms-pagos:
    build: ./ms-pagos
    ports:
      - "5003:5003"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork



  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
